# This is a CircleCI configuration to run decompile3 tests on github branches python-3.7-to-3.10
# as well as the master branch.

version: 2.1
jobs:
  build-python-3-11:
    working_directory: ~/rocky/python-decompyle3
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      COMPILE: --compile
    docker:
    - image: cimg/python:3.11
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: sudo apt update
    - run: sudo apt install python3-pip
    # Until the next xdis release
    - run: sudo pip install git+https://github.com/rocky/python-xdis@python-3.6-to-3.10#egg=xdis
    - run: sudo pip install -e .
    - run: sudo pip install pytest
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: pip install pytest
    - run: pip install -e . && make check
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

  build-python-3-8:
    working_directory: ~/rocky/python-decompyle3
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      COMPILE: --compile
    docker:
    - image: circleci/python:3.8
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: sudo pip install git+https://github.com/rocky/python-xdis@python-3.6-to-3.10#egg=xdis
    - run: sudo pip install -e .
    - run: sudo pip install pytest
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
    - run: sudo python ./setup.py install && make check
    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

workflows:
  version: 2
  build-on-branches:
    jobs:
      - build-python-3-11:
          filters:
            branches:
              only: master
      - build-python-3-8:
          filters:
            branches:
              only: python-3.7-to-3.10
